-- MySQL Script generated by MySQL Workbench
-- Tue Aug  8 17:34:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Seasons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seasons` (
  `IDseasons` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `Number` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`IDseasons`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Series` (
  `IDseries` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Total_seasons` INT UNSIGNED NOT NULL,
  `Seasons_IDseasons` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`IDseries`, `Seasons_IDseasons`),
  INDEX `fk_Series_Seasons1_idx` (`Seasons_IDseasons` ASC) VISIBLE,
  CONSTRAINT `fk_Series_Seasons1`
    FOREIGN KEY (`Seasons_IDseasons`)
    REFERENCES `mydb`.`Seasons` (`IDseasons`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Last_watched`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Last_watched` (
  `IDlast_watched` INT NOT NULL AUTO_INCREMENT,
  `Series_IDseries` INT UNSIGNED NOT NULL,
  `Seasons_IDseasons` INT UNSIGNED NOT NULL,
  `Episode` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`IDlast_watched`, `Series_IDseries`, `Seasons_IDseasons`),
  INDEX `fk_last_watched_Series1_idx` (`Series_IDseries` ASC) VISIBLE,
  INDEX `fk_last_watched_Seasons1_idx` (`Seasons_IDseasons` ASC) VISIBLE,
  CONSTRAINT `fk_last_watched_Series1`
    FOREIGN KEY (`Series_IDseries`)
    REFERENCES `mydb`.`Series` (`IDseries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_last_watched_Seasons1`
    FOREIGN KEY (`Seasons_IDseasons`)
    REFERENCES `mydb`.`Seasons` (`IDseasons`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
